### ISSUE TITLE
Image download broken due to signature issue

### ISSUE THREAD

**Issue by geewiz** [ublue-os/obs-studio-portable#25]
Trying to update my installation today, I got:

```
distrobox-assemble create --replace --file ~/.config/distrobox/obs.ini
 - Deleting obs...
Error: no such container obs
Cannot find container obs.
 - Creating obs...
Trying to pull ghcr.io/ublue-os/obs-studio-portable:latest...
Error: Source image rejected: A signature was required, but no signature exists
```

I assume this is related to the [recent signing key issue](https://universal-blue.discourse.group/t/important-announcement-regarding-system-updates-action-needed/2689/9). Unfortunately, `distrobox` first nuked my OBS installation, rendering me unable to stream.

**Comment by castrojo** [comment]
Merged, it'll be built in a few minutes here when this run goes green, thanks!

https://github.com/ublue-os/obs-studio-portable/actions/runs/9798766368/job/27057757834

**Comment by castrojo** [comment]
https://github.com/ublue-os/obs-studio-portable/actions/runs/9799018673/job/27058480533

Got it, thanks!
